package ar.edu.unlu.poo.corazones.modelo;

public enum Eventos {
    NUEVO_JUGADOR, //SE AGREGO UN JUGADOR
    PARTIDA_INICIADA, // INICIO DE PARTIDA
    PARTIDA_FINALIZADA, // ALGUIEN LLEGO A 100 PUNTOS
    MANO_INICIADA, //SE REPARTIERON LAS CARTAS
    MANO_FINALIZADA,
    CAMBIO_DE_RONDA,
    INTERCAMBIO_REALIZADO,
    TIRO_A_LA_LUNA,
    PUNTOS_ACTUALIZADOS,
    ERROR
}
