package ar.edu.unlu.poo.corazones.modelo;

public enum Eventos {
    NUEVO_JUGADOR, //SE AGREGO UN JUGADOR
    PARTIDA_FINALIZADA, // ALGUIEN LLEGO A 100 PUNTOS
    MANO_INICIADA, //SE REPARTIERON LAS CARTAS
    CAMBIO_DE_RONDA, // CAMBIA nroRonda
    INTERCAMBIO_REALIZADO, // INTERCAMBIO ENTRE JUGADORES REALIZADO
    CORAZONES_ROTOS, // ALGUIEN JUGO UNA CARTA DE CORAZONES
    TIRO_A_LA_LUNA, // ALGUIEN SE LLEVO TODAS LAS CARTAS DE CORAZONES Y REYNA DE PICA
    PUNTOS_ACTUALIZADOS, // ACTUALIZACION DE PUNTOS
}
